name: auto-sync  
on:  
  #schedule:  
  #  - cron: "0 16 * * *"  # 于北京时间 0 点自动执行
  workflow_dispatch:
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
        
      - name: Setup Python  
        uses: actions/setup-python@v3  
        with:  
          python-version: 3.9  
            
      - name: Read Task  
        run: |   
          #git clone git@github.com:/wuliaodexiaoluo/Auto-Sync-Fork.git
          #python -m pip install requests loguru
          #python Sync.py --api-key=xxxxxx --user=wlx --email=wlx@qq.com
          apt -y install wget
          wget https://us.softpedia-secure-download.com/dl/b83f964293144c869339092eb5bdeb42/66685ce0/800000041/apk/Android%20System%20WebView-122.0.6261.119.apk
